apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: od44ya9zw-python
  janus-idp.io/tekton: od44ya9zw-python
  backstage.io/kubernetes-id: od44ya9zw-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: od44ya9zw-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
