apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: od44ya9zw-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: od44ya9zw-python 
  name: od44ya9zw-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: od44ya9zw-python 
